M48
; DRILL file {KiCad 9.0.9-9.0.9~ubuntu24.04.1} date 2026-09-08T19:01:26+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-08T19:01:26+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.9-9.0.9~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
X125.0Y-81.5
X125.0Y-153.5
X209.0Y-81.5
X209.0Y-153.5
M30
